export const seedProducts = [
  {
    name: "INVIROGENS EtBr Destroyer-BAG",
    slug: "etbr-destroyer-bag",
    catalogNumber: "APEBD001",
    category: "EtBr Destroyer",
    shortDescription: "The ready pack INVIROGENS EtBr Destroyer Bag is idea for the treatment of liquid Ethidium Bromide contaminant",
    description: "INVIROGENS EtBr Destroyer is provided in two different formats for the treatment of both solid and liquid Ethidium Bromide contaminant.\nThe ready pack INVIROGENS EtBr Destroyer Bag is ideal for the treatment of liquid Ethidium Bromide contaminant.\nAvailable SKUs: APEBD 001 (20 pack), APEBD 001-1 (10 pack), APEBD 003 (Bag & Sprayer Starter Kit: 5 bags, 1 x 200ml bottle, & 1 sprayer head).\nStore at room temperature.\nEffective: Intended for the removal and destruction of Ethidium Bromide contamination. This effect can be monitored and confirmed by UV light exposure.\nFast: Three liters of double distilled H2O containing 30mg of Ethidium Bromide can be destroyed in a matter of days.\nSafe: Demonstrated by Ames test to safely and effectively destroy EtBr without any mutagenic effect.\nAlso effective against SYBR Green I, SYBR Gold, and SYPRO Orange.",
    components: "APEBD 001 | INVIROGENS EtBr Destroyer Bag: 20 pack\nAPEBD 001-1 | INVIROGENS EtBr Destroyer Bag: 10 pack\nAPEBD 003 | INVIROGENS EtBr Destroyer Bag & Sprayer Starter Kit: 5 bags, 1 x 200ml bottle, & 1 sprayer Head",
    procedure: "Ethidium Bromide containing buffer:\nStep 1: Tear open the package and take out the INVIROGENS EtBr Destroyer Bag. Use the product immediately or seal it into a ziplock bag to avoid prolonged exposure to the air.\nStep 2: Put the EtBr Destroyer into the EtBr-containing buffer. Completely submerge the bag so that the entire Destroyer bag is in the solution.\nStep 3: Destroyer Working Timetable - refer to protocol.\nStep 4: When the treated buffer becomes clear, please use a UV light (254nm) to observe the EtBr-content remaining. If exposure to the UV light displays no fluorescence and the O.D. value is equal to that of d.d.H2O it means that the EtBr containing buffer has been totally destroyed.\nStep 5: The INVIROGENS EtBr Destroyer Bag has absorbed and destroyed all of the EtBr content in the liquid. Following treatment the bag can be thrown away as a non-hazardous item.\n\nEthidium Bromide containing gels:\nStep 1: Tear open the package and take out the INVIROGENS EtBr Destroyer Bag onto the container which fills with 3L d.d.H2O.\nStep 2: 30 minutes later, you can drop the EtBr-contaminated gels into this container.\nStep 3: You can drop as many gels into the container during the 6 months period, but the total amount of EtBr in all gels cannot exceed 30mg.\nStep 4: When the treated gel becomes clear, please use the UV light box (UV Wavelength 254nm) to ensure the Ethidium Bromide has been totally destroyed.\n\nAlso effective against SYBR Green I (use 488nm UV), SYBR Gold (use 488nm UV), and SYPRO Orange (use 488nm UV).",
    specifications: "INVIROGENS EtBr Destroyer is provided in two different formats for the treatment of both solid and liquid Ethidium Bromide contaminant.\n\nEffective: A laboratory reagent intended for the removal and destruction of Ethidium Bromide contamination. This effect can be monitored and confirmed by UV light exposure.\nFast: Three liters of double distilled H2O containing 30mg of Ethidium Bromide can be destroyed in a matter of days.\nSpecific: Two specific designs for different purposes: EtBr Destroyer bags and EtBr Destroyer Spray.\nEconomical: Sprayer bottles can be refilled. Bags available in 10 and 20 packs. You can re-use your buffer after treatment!\nSafe: Demonstrated by Ames test to safely and effectively destroy EtBr without any mutagenic effect.",
    troubleshooting: "If EtBr fluorescence persists after treatment:\n- Ensure the Destroyer Bag was fully submerged in the solution.\n- Check that the total EtBr amount does not exceed the recommended capacity.\n- Extend the treatment time according to the protocol timetable.\n- For gel treatment, ensure the solution covers the entire gel.\n- Use appropriate UV wavelength for the specific stain being treated (254nm for EtBr, 488nm for SYBR Green/Gold and SYPRO Orange).",
    image: "/images/products/etbr-destroyer-bag.jpg",
    featured: true,
  },
  {
    name: "INVIROGENS EtBr Destroyer-SPRAYER",
    slug: "etbr-destroyer-sprayer",
    catalogNumber: "APEBD002",
    category: "EtBr Destroyer",
    shortDescription: "Sprayer can be used for the treatment of solid contaminant waste including electrophoresis gels, glassware, paper towels, gloves, laboratory equipment, bench surface etc",
    description: "INVIROGENS EtBr Destroyer Sprayer can be used for the treatment of solid contaminant waste including electrophoresis gels, glassware, paper towels, gloves, laboratory equipment, bench surface etc.\nAvailable SKUs: APEBD002 (Sprayer Pack: 2 x 200ml bottles and 1 sprayer head), APEBD002-1 (Supplement: 2 x 200ml refill bottles), APEBD002-2 (Supplement: 1 x 1L refill bottle).\nStore at room temperature.\nFor general protection of uncontaminated area, spray the EtBr Destroyer on the entire working area, leave for about 5 minutes, then wipe it dry with paper towel.\nEconomical: Sprayer bottles can be refilled after use. You can even re-use your buffer after treatment!\nSafe: Demonstrated by Ames test to safely and effectively destroy EtBr without any mutagenic effect.",
    components: "APEBD002 | EtBr Destroyer Sprayer Pack: 2 x 200ml bottles and 1 sprayer head\nAPEBD002-1 | EtBr Destroyer Supplement: 2 x 200ml refill bottles, no sprayer head\nAPEBD002-2 | EtBr Destroyer Supplement: 1 x 1L refill bottle, no sprayer head\nAPEBD 003 | EtBr Destroyer Bag & Sprayer Kit: 5 bags, 1 x 200ml bottle, & 1 sprayer Head",
    procedure: "Step 1: Open the bottle cap of the sprayer and insert the sprayer head. The sprayer head has to be screwed onto the bottle tightly.\nStep 2: Spray onto the contaminated target area. The liquid has to completely cover the entire contaminant.\nStep 3: For general protection - spray the whole working area and wipe down after 5 minutes. For known contaminated area, spray on the specific working area following the protocol timetable.\nStep 4: Use a portable UV light box (UV Wavelength 254nm) to ensure the Ethidium Bromide has been totally destroyed.\n\nAlso effective against SYBR Green I, SYBR Gold, and SYPRO Orange (use 488nm UV for these stains).",
    specifications: "INVIROGENS EtBr Destroyer is provided in two different formats for the treatment of both solid and liquid Ethidium Bromide contaminant.\n\nEffective: A laboratory reagent intended for the removal and destruction of Ethidium Bromide contamination. This effect can be monitored and confirmed by UV light exposure.\nFast: For general protection, spray and wipe after 5 minutes.\nSpecific: Two specific designs for different purposes: EtBr Destroyer bags and EtBr Destroyer Spray.\nEconomical: Sprayer bottles can be refilled. You can re-use your buffer after treatment!\nSafe: Demonstrated by Ames test to safely and effectively destroy EtBr without any mutagenic effect.",
    troubleshooting: "If EtBr fluorescence persists after treatment:\n- Ensure the entire contaminated area was covered with spray.\n- Extend the contact time according to the protocol.\n- Apply additional spray for heavily contaminated areas.\n- Use appropriate UV wavelength for the specific stain (254nm for EtBr, 488nm for SYBR Green/Gold and SYPRO Orange).",
    image: "/images/products/etbr-destroyer-sprayer.jpg",
    featured: true,
  },
  {
    name: "PCR Clean-Up Mini Kit",
    slug: "pcr-cleanup-mini-kit",
    catalogNumber: "APPCK004/050/200",
    category: "DNA Clean-Up",
    shortDescription: "For purification of PCR products or reaction mixtures (concentration and desalination of reaction mixtures).",
    description: "INVIROGENS \u03B1+ Solution\u2122 PCR Clean-Up Mini Kit for rapid purification of PCR products.\nAvailable in 4 preps (APPCK004), 50 preps (APPCK050), and 200 preps (APPCK200).\nPrinciple: spin column (silica matrix).\nDNA Binding capacity: 20 \u03BCg per column.\nSample size: up to 100 \u03BCl of reaction solution.\nDNA size: 65 bp to 10 kbp.\nRecovery: 90% to 95% for PCR clean-up.\nOperation time: 10 to 15 minutes.\nElution volume: 40 \u03BCl.\nStore at room temperature (15-25\u00B0C) for 2 years.",
    components: "| | APPCK 004 (4 preps) | APPCK 050 (50 preps) | APPCK 200 (200 preps) |\n|---|---|---|---|\n| PC Buffer | 1.5 ml | 25 ml | 100 ml |\n| Wash Buffer (concentrate) | 1 ml | 10 ml | 40 ml |\n| Elution Buffer | 1.5 ml | 15 ml | 50 ml |\n| PC Mini Column | 4 pcs | 50 pcs | 200 pcs |\n| Collection Tube | 4 pcs | 50 pcs | 200 pcs |\n| Elution Tube | 4 pcs | 50 pcs | 200 pcs |\n| User Manual | 1 | 1 | 1 |",
    procedure: "1. Transfer up to 100 ul of PCR product into a 1.5 ml microcentrifuge tube.\n2. Add 5 volumes of PC Buffer to the PCR product and mix by vortexing.\n3. Transfer the mixture to a PC Mini Column placed in a Collection Tube.\n4. Centrifuge at full speed for 30 seconds. Discard the flow-through.\n5. Add 700 ul of Wash Buffer to the column and centrifuge for 30 seconds.\n6. Discard the flow-through and centrifuge for an additional 2 minutes to dry the column.\n7. Place the column in a new Elution Tube.\n8. Add 40 ul of Elution Buffer to the center of the column membrane.\n9. Stand for 2 minutes, then centrifuge for 2 minutes to elute the DNA.",
    specifications: "Principle: spin column (silica matrix)\nDNA Binding capacity: 20 ug per column\nSample size: up to 100 ul of reaction solution\nDNA size: 65 bp to 10 kbp\nRecovery: 90% to 95%\nOperation time: 10 to 15 minutes\nElution volume: 40 ul\nStore at room temperature (15-25\u00B0C) for 2 years\n\nImportant Notes:\n- Buffers contain irritants. Wear gloves and lab coat.\n- Add ethanol (96-100%) to Wash Buffer before first use.\n- Heat Elution Buffer to 65\u00B0C before use.\n- All centrifuge steps at full speed (~18,000 x g).",
    troubleshooting: "Low DNA yield:\n- Ensure correct volume of ethanol was added to Wash Buffer.\n- Verify sample was properly mixed with PC Buffer.\n- Check that column was not overloaded.\n\nDNA size is smaller than expected:\n- Gel extraction may be required for specific fragment isolation.\n- Verify PCR conditions and template quality.",
    image: "/images/products/pcr-cleanup-mini-kit.jpg",
    featured: false,
  },
  {
    name: "GEL/PCR Purification Kit",
    slug: "gel-pcr-purification-kit",
    catalogNumber: "APGCK004/050/100/300",
    category: "DNA Clean-Up",
    shortDescription: "Sample size: 1-5 ml culture cells.",
    description: "INVIROGENS \u03B1+ Solution\u2122 GEL/PCR Purification Kit for gel extraction and PCR clean-up.\nAvailable in 4 preps (APGCK004), 50 preps (APGCK050), 100 preps (APGCK100), and 300 preps (APGCK300).\nPrinciple: spin column (silica matrix).\nDNA Binding capacity: 20 \u03BCg per column.\nSample size: up to 300 mg of agarose gel.\nDNA size: 65 bp to 10 kbp.\nRecovery: 70% to 85% for Gel extraction, 90% to 95% for PCR clean-up.\nOperation time: 10 to 20 minutes.",
    components: "| | APGCK 004 (4 preps) | APGCK 050 (50 preps) | APGCK 100 (100 preps) | APGCK 300 (300 preps) |\n|---|---|---|---|---|\n| DF Buffer | 1.5 ml | 25 ml | 50 ml | 150 ml |\n| Wash Buffer (concentrate) | 1 ml | 10 ml | 20 ml | 50 ml |\n| Elution Buffer | 1.5 ml | 15 ml | 30 ml | 80 ml |\n| DF Column | 4 pcs | 50 pcs | 100 pcs | 300 pcs |\n| Collection Tube | 4 pcs | 50 pcs | 100 pcs | 300 pcs |\n| User Manual | 1 | 1 | 1 | 1 |",
    procedure: "For Gel Extraction:\n1. Excise the DNA fragment from the agarose gel using a clean scalpel.\n2. Weigh the gel slice and add 3 volumes of DF Buffer per volume of gel (100 mg ~ 100 ul).\n3. Incubate at 55-60\u00B0C for 10 minutes or until gel is completely dissolved. Mix every 2-3 minutes.\n4. Transfer dissolved gel to DF Column in Collection Tube.\n5. Centrifuge at full speed for 30 seconds. Discard flow-through.\n6. Add 700 ul Wash Buffer. Centrifuge for 30 seconds.\n7. Centrifuge for additional 2 minutes to dry column.\n8. Place column in new tube. Add Elution Buffer, stand 2 minutes, centrifuge to elute.",
    specifications: "Principle: spin column (silica matrix)\nDNA Binding capacity: 20 ug per column\nSample size: up to 300 mg of agarose gel\nDNA size: 65 bp to 10 kbp\nRecovery: 70-85% for Gel extraction, 90-95% for PCR clean-up\nOperation time: 10-20 minutes\nStore at room temperature (15-25\u00B0C) for 2 years\n\nImportant Notes:\n- Add ethanol (96-100%) to Wash Buffer before first use.\n- Ensure gel is completely dissolved before loading.\n- Heat Elution Buffer to 65\u00B0C before use.",
    troubleshooting: "Low DNA recovery from gel:\n- Ensure gel was completely dissolved at 55-60\u00B0C.\n- Do not overheat (>60\u00B0C) as this may damage DNA.\n- Use fresh gel for best results.\n\nSmeared DNA:\n- Reduce the size of gel slice to minimize agarose amount.\n- Ensure complete dissolution before column loading.",
    image: "/images/products/gel-pcr-purification-kit.jpg",
    featured: false,
  },
  {
    name: "Genomic DNA Clean-Up Kit",
    slug: "genomic-dna-cleanup-kit",
    catalogNumber: "APGDC004/050/200",
    category: "DNA Extraction",
    shortDescription: "Sample size: up to 100 ul of reaction solution.",
    description: "INVIROGENS \u03B1+ Solution\u2122 Genomic DNA Clean-Up Kit for purification of genomic DNA.\nAvailable in 4 preps (APGDC004), 50 preps (APGDC050), and 200 preps (APGDC200).\nSample size: up to 100 \u03BCl of reaction solution.\nSpin column based purification with silica matrix.",
    components: "| | APGDC 004 (4 preps) | APGDC 050 (50 preps) | APGDC 200 (200 preps) |\n|---|---|---|---|\n| GC Buffer | 1.5 ml x 2 | 30 ml | 120 ml |\n| Wash Buffer (concentrate) | 1 ml | 10 ml | 40 ml |\n| Elution Buffer | 1.5 ml | 15 ml | 50 ml |\n| GC Mini Column | 4 pcs | 50 pcs | 200 pcs |\n| Collection Tube | 4 pcs | 50 pcs | 200 pcs |\n| Elution Tube | 4 pcs | 50 pcs | 200 pcs |\n| User Manual | 1 | 1 | 1 |",
    procedure: "1. Add 5 volumes of GC Buffer to the DNA sample and mix well.\n2. Transfer to GC Mini Column in Collection Tube.\n3. Centrifuge at 10,000 x g for 30 seconds. Discard flow-through.\n4. Add 700 ul Wash Buffer. Centrifuge for 30 seconds.\n5. Discard flow-through. Centrifuge for 2 minutes to dry column.\n6. Place column in new Elution Tube.\n7. Add 50 ul preheated (65\u00B0C) Elution Buffer to center of membrane.\n8. Stand for 2 minutes, then centrifuge to elute DNA.",
    specifications: "Principle: spin column (silica matrix)\nDNA Binding capacity of spin column: 50 ug\nSample size: up to 100 ul of reaction solution\nRecovery: 80% to 95%\nOperation time: 10 to 15 min\nElution volume: 50 ul\n\nImportant Notes:\n- Buffers contain irritants. Wear gloves and lab coat.\n- Add ethanol (96-100%) to Wash Buffer before use.\n- Centrifugation steps at 10,000 x g in a microcentrifuge.\n- Heat Elution Buffer to 65\u00B0C before use.",
    troubleshooting: "Low DNA yield:\n- Ensure correct volume of ethanol added to Wash Buffer.\n- Pre-heat Elution Buffer to 65\u00B0C.\n- Incubate column with Elution Buffer for 2 minutes before centrifugation.\n\nDNA contaminated with salt:\n- Ensure wash step was performed completely.\n- Add additional wash step if needed.",
    image: "/images/products/genomic-dna-cleanup-kit.jpg",
    featured: false,
  },
  {
    name: "Blood Genomic DNA Extraction Mini Kit",
    slug: "blood-genomic-dna-extraction",
    catalogNumber: "APBGK004/050/100/200",
    category: "DNA Extraction",
    shortDescription: "Sample size: up to 200 ul whole blood/serum/plasma/body fluids, or up to 5 x 10^6 cultured cells.",
    description: "INVIROGENS \u03B1+ Solution\u2122 Blood Genomic DNA Extraction Mini Kit for efficient DNA isolation.\nAvailable in 4 preps (APBGK004), 50 preps (APBGK050), 100 preps (APBGK100), and 200 preps (APBGK200).\nSample size: Up to 200 \u03BCl whole blood, serum, plasma, body fluids; Up to 5 x 10\u2076 cultured cells.",
    components: "| | APBGK 004 (4 preps) | APBGK 050 (50 preps) | APBGK 100 (100 preps) | APBGK 200 (200 preps) |\n|---|---|---|---|---|\n| BG Buffer | 1.5 ml | 15 ml | 30 ml | 60 ml |\n| GW Buffer (concentrate) | 1.3 ml | 22 ml | 44 ml | 88 ml |\n| Wash Buffer (concentrate) | 1 ml | 10 ml | 20 ml | 40 ml |\n| Elution Buffer | 1 ml | 15 ml | 30 ml | 60 ml |\n| Proteinase K | 1 mg | 11 mg | 11 mg x 2 | 11 mg x 4 |\n| BG Mini Column | 4 pcs | 50 pcs | 100 pcs | 200 pcs |\n| Collection Tube | 8 pcs | 100 pcs | 200 pcs | 400 pcs |\n| Elution Tube | 4 pcs | 50 pcs | 100 pcs | 200 pcs |\n| User Manual | 1 | 1 | 1 | 1 |",
    procedure: "1. Add 200 ul of whole blood sample to a 1.5 ml microcentrifuge tube.\n2. Add 20 ul of Proteinase K stock solution and 200 ul of BG Buffer. Mix by vortexing.\n3. Incubate at 60\u00B0C for 10 minutes.\n4. Add 200 ul of ethanol (96-100%). Mix by vortexing.\n5. Transfer to BG Mini Column in Collection Tube. Centrifuge at full speed for 1 minute.\n6. Add 500 ul of GW Buffer. Centrifuge for 30 seconds.\n7. Add 700 ul of Wash Buffer. Centrifuge for 30 seconds.\n8. Centrifuge for 2 minutes to dry column.\n9. Place column in Elution Tube. Add 50-200 ul of preheated Elution Buffer.\n10. Stand 2 minutes, centrifuge to elute.",
    specifications: "Principle: mini spin column (silica matrix)\nSample size: Up to 200 ul whole blood, serum, plasma, body fluids; Up to 5 x 10^6 cultured cells\nOperation time: 30 minutes\nBinding capacity: up to 60 ug total DNA / column\nExpected yield: 4-8 ug / prep\nColumn applicability: centrifugation and vacuum\nMinimum elution volume: 50 ul\n\nImportant Notes:\n- Add 1.1 ml sterile ddH2O to Proteinase K tube to make 10 mg/ml stock. Store at 4\u00B0C.\n- Add ethanol (96-100%) to GW Buffer and Wash Buffer when first opened.\n- Prepare dry baths or water baths to 60\u00B0C for lysis step.",
    troubleshooting: "Low or no yield of genomic DNA:\n- Incorrect preparation of Wash Buffer: Ensure ethanol (96-100%) is added.\n- Elution not efficient: Stand column with Elution Buffer for 2 min before centrifugation. Ensure pH 7.5-8.5.\n\nColumn is clogged:\n- Sample too viscous. Reduce sample volume.\n\nDegradation of eluted DNA:\n- Sample is old. Always use fresh or well-stored samples.",
    image: "/images/products/invirogens-placeholder.svg",
    featured: true,
  },
  {
    name: "Blood/Cultured Cell Genomic DNA Extraction Mini Kit",
    slug: "blood-cultured-cell-dna-extraction",
    catalogNumber: "APBGR004/100/200",
    category: "DNA Extraction",
    shortDescription: "Sample size: up to 300 ul whole blood, 200 ul frozen blood/buffy coat, and cultured cells.",
    description: "INVIROGENS \u03B1+ Solution\u2122 Blood/Cultured Cell Genomic DNA Extraction Mini Kit.\nAvailable in 4 preps (APBGR004), 100 preps (APBGR100), and 200 preps (APBGR200).\nSample size: Up to 300 \u03BCl of whole blood; Up to 200 \u03BCl of frozen blood; Up to 200 \u03BCl of buffy coat; Up to 1 x 10\u2077 cultured animal cells; Up to 1 x 10\u2079 cultured bacterial cells.",
    components: "| | APBGR 004 (4 preps) | APBGR 100 (100 preps) | APBGR 200 (200 preps) |\n|---|---|---|---|\n| RBC Lysis Buffer | 7 ml | 135 ml | 270 ml |\n| TG Buffer | 1.5 ml | 30 ml | 60 ml |\n| BG Buffer | 1.5 ml | 40 ml | 80 ml |\n| BW Buffer | 1.5 ml x 2 | 45 ml | 90 ml |\n| Wash Buffer (concentrate) | 1 ml | 25 ml | 35 ml |\n| Elution Buffer | 1.5 ml | 30 ml | 60 ml |\n| BG Mini Column | 4 pcs | 100 pcs | 200 pcs |\n| Collection Tube | 8 pcs | 200 pcs | 400 pcs |\n| User Manual | 1 | 1 | 1 |",
    procedure: "For Whole Blood:\n1. Add 3 volumes of RBC Lysis Buffer to blood sample. Mix by inverting.\n2. Incubate at room temperature for 5 minutes.\n3. Centrifuge at 3,000 x g for 5 minutes. Discard supernatant.\n4. Add 200 ul TG Buffer and 20 ul Proteinase K. Vortex.\n5. Incubate at 60\u00B0C for 15 minutes.\n6. Add 200 ul BG Buffer. Mix. Add 200 ul ethanol. Mix.\n7. Transfer to BG Column. Centrifuge 1 minute.\n8. Wash with BW Buffer (500 ul), then Wash Buffer (700 ul).\n9. Dry column by centrifugation for 2 minutes.\n10. Elute with 50-200 ul preheated Elution Buffer.",
    specifications: "Principle: mini spin column (silica matrix)\nSample size: Up to 300 ul whole blood; Up to 200 ul frozen blood; Up to 200 ul buffy coat; Up to 1 x 10^7 cultured animal cells; Up to 1 x 10^9 cultured bacterial cells\nOperation time: 30 minutes\nBinding capacity: up to 60 ug total DNA / column\nExpected yield: 4-8 ug / prep\nColumn applicability: centrifugation and vacuum\nMinimum elution volume: 50 ul\n\nImportant Notes:\n- Add ethanol (96-100%) to Wash Buffer when first opened.",
    troubleshooting: "Low or no yield:\n- Incorrect Wash Buffer preparation: Ensure ethanol (96-100%) added.\n- Elution not efficient: Stand 2 min before centrifugation. Ensure pH 7.5-8.5.\n\nColumn clogged:\n- Sample too viscous. Reduce sample volume.\n\nDNA degradation:\n- Use fresh or well-stored samples.",
    image: "/images/products/invirogens-placeholder.svg",
    featured: false,
  },
  {
    name: "Plant Genomic DNA Extraction Mini Kit",
    slug: "plant-genomic-dna-extraction",
    catalogNumber: "APPGK004/050/100",
    category: "DNA Extraction",
    shortDescription: "Sample size: wet weight <= 100 mg; dry weight <= 20 mg.",
    description: "INVIROGENS \u03B1+ Solution\u2122 Plant Genomic DNA Extraction Mini Kit.\nAvailable in 4 preps (APPGK004), 50 preps (APPGK050), and 100 preps (APPGK100).\nSample size: Wet weight up to 100 mg; Dry weight up to 20 mg.",
    components: "| | APPGK 004 (4 preps) | APPGK 050 (50 preps) | APPGK 100 (100 preps) |\n|---|---|---|---|\n| PG1 Buffer | 2 ml | 25 ml | 55 ml |\n| PG2 Buffer | 1 ml | 8 ml | 15 ml |\n| PG3 Buffer (concentrate) | 1.5 ml | 15 ml | 30 ml |\n| GW Buffer (concentrate) | 0.8 ml | 13 ml | 26 ml |\n| Wash Buffer (concentrate) | 1.5 ml | 15 ml | 30 ml |\n| Elution Buffer | 1.5 ml | 15 ml | 30 ml |\n| RNase A (lyophilized) | 1.5 mg | 22 mg | 43 mg |\n| Filter Column | 4 pcs | 50 pcs | 100 pcs |\n| PG Column | 4 pcs | 50 pcs | 100 pcs |\n| Collection Tube | 8 pcs | 100 pcs | 200 pcs |\n| User Manual | 1 | 1 | 1 |",
    procedure: "1. Grind plant tissue (up to 100 mg fresh or 20 mg dry weight) in liquid nitrogen.\n2. Add 400 ul PG1 Buffer and 4 ul RNase A. Vortex vigorously.\n3. Incubate at 65\u00B0C for 10 minutes.\n4. Add 100 ul PG2 Buffer. Mix by inverting. Incubate on ice for 3 minutes.\n5. Centrifuge at full speed for 5 minutes.\n6. Transfer supernatant to Filter Column. Centrifuge.\n7. Add 1.5 volumes PG3 Buffer to filtrate. Mix.\n8. Transfer to PG Column. Centrifuge.\n9. Wash with 500 ul GW Buffer, then 700 ul Wash Buffer.\n10. Dry column. Elute with preheated Elution Buffer.",
    specifications: "Principle: mini spin column (silica matrix)\nSample size: Wet weight up to 100 mg; Dry weight up to 20 mg\nOperation time: 30-60 minutes\nBinding capacity: up to 60 ug total DNA / column\nExpected yield: 5-40 ug / prep\nColumn applicability: centrifugation and vacuum\nMinimum elution volume: 50 ul\n\nImportant Notes:\n- Check PG1 Buffer before use. Warm at 60\u00B0C for 5 min if precipitate formed.\n- Preheat dry baths to 65\u00B0C before operation.\n- Add ethanol (96-100%) to PG3 Buffer, GW and Wash before use.\n- Store RNase A at -20\u00B0C. Add sterile ddH2O to make 50 mg/ml stock.",
    troubleshooting: "Low DNA yield:\n- Ensure tissue was thoroughly ground in liquid nitrogen.\n- Verify correct ethanol volume added to buffers.\n- Pre-heat Elution Buffer to improve elution.\n\nDNA degradation:\n- Use fresh plant tissue. Old or improperly stored tissue yields degraded DNA.\n- Ensure RNase A was properly reconstituted.",
    image: "/images/products/invirogens-placeholder.svg",
    featured: false,
  },
  {
    name: "Tissue Genomic DNA Extraction Mini Kit",
    slug: "tissue-genomic-dna-extraction",
    catalogNumber: "APTGK004/050/100/200",
    category: "DNA Extraction",
    shortDescription: "For extraction genomic DNA from animal cells, animal tissues, blood, bacteria, paraffin fixed tissue, yeast and fungi",
    description: "INVIROGENS \u03B1+ Solution\u2122 Tissue Genomic DNA Extraction Mini Kit.\nAvailable in 4 preps (APTGK004), 50 preps (APTGK050), 100 preps (APTGK100), and 200 preps (APTGK200).\nPrinciple: mini spin column (silica matrix).\nSample size: Up to 25 mg animal tissue; 1.2 cm mouse tail; Up to 10\u2077 cultured cells.",
    components: "| | APTGK 004 (4 preps) | APTGK 050 (50 preps) | APTGK 100 (100 preps) | APTGK 200 (200 preps) |\n|---|---|---|---|---|\n| TG1 Buffer | 1.5 ml | 15 ml | 30 ml | 60 ml |\n| TG2 Buffer | 1.5 ml | 15 ml | 30 ml | 60 ml |\n| Proteinase K (lyophilized) | 1 mg | 11 mg | 11 mg x 2 | 11 mg x 4 |\n| GW Buffer (concentrate) | 1.3 ml | 22 ml | 44 ml | 88 ml |\n| Wash Buffer (concentrate) | 1 ml | 10 ml | 20 ml | 40 ml |\n| Elution Buffer | 1 ml | 15 ml | 30 ml | 60 ml |\n| TG Mini Column | 4 pcs | 50 pcs | 100 pcs | 200 pcs |\n| Collection Tube | 8 pcs | 100 pcs | 200 pcs | 400 pcs |\n| Elution Tube | 4 pcs | 50 pcs | 100 pcs | 200 pcs |\n| User Manual | 1 | 1 | 1 | 1 |",
    procedure: "1. Cut up to 25 mg tissue into small pieces.\n2. Add 200 ul TG1 Buffer and 20 ul Proteinase K stock solution.\n3. Incubate at 60\u00B0C for 1-3 hours (or overnight) until tissue is completely lysed.\n4. Add 200 ul TG2 Buffer. Mix. Incubate at 70\u00B0C for 10 minutes.\n5. Add 200 ul ethanol (96-100%). Mix well.\n6. Transfer to TG Mini Column. Centrifuge.\n7. Wash with 500 ul GW Buffer, then 700 ul Wash Buffer.\n8. Dry column by centrifugation for 2 minutes.\n9. Elute with 50-200 ul preheated (70\u00B0C) Elution Buffer.",
    specifications: "Principle: mini spin column (silica matrix)\nSample size: Up to 25 mg animal tissue; 1.2 cm mouse tail; Up to 10^7 cultured cells\nOperation time: 30-60 minutes\nBinding capacity: up to 60 ug total DNA / column\nExpected yield: 15-35 ug / prep\nColumn applicability: centrifugation and vacuum\nMinimum elution volume: 50 ul\n\nImportant Notes:\n- Add 1.1 ml sterile ddH2O to Proteinase K to make 10 mg/ml stock. Store at 4\u00B0C.\n- Add ethanol (96-100%) to GW Buffer and Wash Buffer when first opened.\n- Prepare dry baths: 60\u00B0C for lysis and 70\u00B0C for step 4.\n- Preheat Elution Buffer to 70\u00B0C.\n- All centrifuge steps at full speed (~18,000 x g).",
    troubleshooting: "Low DNA yield:\n- Ensure tissue was completely lysed (extend Proteinase K digestion time).\n- Verify Proteinase K was properly reconstituted.\n- Pre-heat Elution Buffer to 70\u00B0C.\n\nColumn clogged:\n- Reduce tissue amount. Ensure complete lysis before loading.",
    image: "/images/products/invirogens-placeholder.svg",
    featured: true,
  },
  {
    name: "High Yield Plasmid Extraction Mini Kit",
    slug: "high-yield-plasmid-extraction",
    catalogNumber: "APHPD004/100/300",
    category: "Plasmid Extraction",
    shortDescription: "Sample size: 1-5 ml culture cells.",
    description: "INVIROGENS \u03B1+ Solution\u2122 High Yield Plasmid Extraction Mini Kit.\nAvailable in 4 preps (APHPD004), 100 preps (APHPD100), and 300 preps (APHPD300).\nPrinciple: mini spin column (silica matrix).\nSample size: 1 to 5 ml bacterial culture.",
    components: "| | APHPD 004 (4 preps) | APHPD 100 (100 preps) | APHPD 300 (300 preps) |\n|---|---|---|---|\n| PD1 Buffer | 2 ml | 40 ml | 120 ml |\n| PD2 Buffer | 2 ml | 40 ml | 120 ml |\n| PD3 Buffer | 2 ml | 40 ml | 120 ml |\n| PDW Buffer | 1.5 ml | 30 ml | 75 ml |\n| Wash Buffer (concentrate) | 1 ml | 20 ml | 50 ml |\n| Elution Buffer | 1 ml | 15 ml | 30 ml |\n| PD Column | 4 pcs | 100 pcs | 300 pcs |\n| Collection Tube | 8 pcs | 200 pcs | 600 pcs |\n| RNase A | 40 ul | 1 ml | 3 ml |\n| User Manual | 1 | 1 | 1 |",
    procedure: "1. Pellet 1-5 ml of overnight bacterial culture by centrifugation.\n2. Resuspend pellet in 200 ul PD1 Buffer (with RNase A added).\n3. Add 200 ul PD2 Buffer. Mix gently by inverting 6-8 times. Incubate for 2 minutes.\n4. Add 300 ul PD3 Buffer. Mix immediately by inverting 6-8 times.\n5. Centrifuge at full speed for 10 minutes.\n6. Transfer supernatant to PD Column. Centrifuge.\n7. Add 500 ul PDW Buffer. Centrifuge.\n8. Add 700 ul Wash Buffer. Centrifuge.\n9. Centrifuge for 2 minutes to dry column.\n10. Elute with 30-50 ul Elution Buffer.",
    specifications: "Principle: mini spin column (silica matrix)\nSample size: 1-5 ml bacterial culture\nSize of plasmid or construct: < 15 kb\nOperation time: < 25 minutes\nTypical Yield: 25-40 ug\nBinding capacity: 60 ug per column\nColumn applicability: centrifugation and vacuum\n\nImportant Notes:\n- Add RNase A to PD1 Buffer before first use.\n- Add ethanol (96-100%) to Wash Buffer.\n- Do not allow lysis (step 3) to exceed 5 minutes.",
    troubleshooting: "Low plasmid yield:\n- Use fresh overnight culture (12-16 hours).\n- Ensure RNase A was added to PD1 Buffer.\n- Do not overload column capacity.\n\nPlasmid contaminated with genomic DNA:\n- Do not vortex during lysis step.\n- Mix gently by inversion only.\n- Ensure lysis time does not exceed 5 minutes.",
    image: "/images/products/high-yield-plasmid-extraction.jpg",
    featured: true,
  },
  {
    name: "Plasmid Extraction Mini Kit",
    slug: "plasmid-extraction-mini-kit",
    catalogNumber: "APPDE004/050/100/300",
    category: "Plasmid Extraction",
    shortDescription: "Sample size: 1-5 ml culture cells.",
    description: "INVIROGENS \u03B1+ Solution\u2122 Plasmid Extraction Mini Kit for reliable plasmid DNA purification.\nAvailable in 4 preps (APPDE004), 50 preps (APPDE050), 100 preps (APPDE100), and 300 preps (APPDE300).\nSample size: 1 to 5 ml culture cells.",
    components: "| | APPDE 004 (4 preps) | APPDE 050 (50 preps) | APPDE 100 (100 preps) | APPDE 300 (300 preps) |\n|---|---|---|---|---|\n| PD1 Buffer | 2 ml | 15 ml | 30 ml | 90 ml |\n| PD2 Buffer | 2 ml | 15 ml | 30 ml | 90 ml |\n| PD3 Buffer | 2 ml | 15 ml | 30 ml | 90 ml |\n| Wash Buffer (concentrate) | 1 ml | 10 ml | 20 ml | 50 ml |\n| Elution Buffer | 1 ml | 15 ml | 30 ml | 60 ml |\n| PD Column | 4 pcs | 50 pcs | 100 pcs | 300 pcs |\n| Collection Tube | 8 pcs | 100 pcs | 200 pcs | 600 pcs |\n| RNase A | 40 ul | 500 ul | 1 ml | 3 ml |\n| User Manual | 1 | 1 | 1 | 1 |",
    procedure: "1. Pellet 1-5 ml of overnight bacterial culture.\n2. Resuspend in 200 ul PD1 Buffer (with RNase A).\n3. Add 200 ul PD2 Buffer. Mix by inverting 6-8 times. Incubate 2 minutes.\n4. Add 300 ul PD3 Buffer. Mix immediately by inverting.\n5. Centrifuge at full speed for 10 minutes.\n6. Transfer clear supernatant to PD Column. Centrifuge.\n7. Add 700 ul Wash Buffer. Centrifuge.\n8. Centrifuge 2 minutes to dry.\n9. Elute with 30-50 ul Elution Buffer.",
    specifications: "Principle: mini spin column (silica matrix)\nSample size: 1-5 ml culture cells\nModified alkaline lysis method\nSilica membrane spin columns for rapid purification\nPurified plasmid suitable for restriction digestion, cloning, sequencing, and transformation\n\nImportant Notes:\n- Add RNase A to PD1 Buffer before first use.\n- Add ethanol (96-100%) to Wash Buffer when first opened.",
    troubleshooting: "Low yield:\n- Use fresh overnight culture (12-16 hours).\n- Ensure RNase A added to PD1.\n\nGenomic DNA contamination:\n- Do not vortex during lysis. Mix by gentle inversion only.",
    image: "/images/products/plasmid-extraction-mini-kit.jpg",
    featured: false,
  },
  {
    name: "RNase Destroyer Sprayer",
    slug: "rnase-destroyer-sprayer",
    catalogNumber: "APRND001",
    category: "RNase Destroyer",
    shortDescription: "RNase Destroyer Sprayer and Sprayer supplement",
    description: "INVIROGENS RNase Destroyer Sprayer and Sprayer Supplement.\nEffectively eliminates RNase contamination from surfaces, pipettes, and labware.\nAlso removes DNA contamination for a completely nuclease-free workspace.\nReady-to-use spray format for convenient application.\nNon-toxic and non-corrosive formulation safe for laboratory equipment.",
    components: "APRND001 | RNase Destroyer Sprayer: 1 x 500ml bottle with sprayer head\nAPRND001-1 | RNase Destroyer Supplement: 1 x 500ml refill bottle",
    procedure: "1. Spray RNase Destroyer onto the surface to be decontaminated.\n2. Ensure the entire surface is covered with the solution.\n3. Wipe the surface with a clean paper towel after 1-2 minutes.\n4. The treated surface is now free of RNase and DNA contamination.\n5. For pipettes and small equipment, spray directly and wipe clean.\n6. For glassware, spray inside and outside surfaces, then rinse with RNase-free water.",
    specifications: "Ready-to-use spray format for convenient application\nEffectively eliminates RNase and DNA contamination\nNon-toxic and non-corrosive formulation\nSafe for laboratory equipment including pipettes, glassware, and plasticware\nEssential for maintaining RNase-free conditions in RNA research",
    troubleshooting: "RNase contamination persists:\n- Ensure complete surface coverage.\n- Allow sufficient contact time before wiping.\n- Re-spray if working with heavily contaminated surfaces.\n- For stubborn contamination, soak equipment in the solution.",
    image: "/images/products/rnase-destroyer-sprayer.jpg",
    featured: true,
  },
  {
    name: "Plant Total RNA Mini Kit",
    slug: "plant-total-rna-mini-kit",
    catalogNumber: "APPRK004/050/100",
    category: "RNA Extraction",
    shortDescription: "Sample size: up to 100 mg plant tissue or 1 x 10^7 plant cells.",
    description: "INVIROGENS \u03B1+ Solution\u2122 Plant Total RNA Mini Kit.\nAvailable in 4 preps (APPRK004), 50 preps (APPRK050), and 100 preps (APPRK100).\nSample size: up to 100 mg plant tissue or 1 x 10\u2077 plant cells.",
    components: "| | APPRK 004 (4 preps) | APPRK 050 (50 preps) | APPRK 100 (100 preps) |\n|---|---|---|---|\n| PRK Buffer | 2 ml | 25 ml | 50 ml |\n| RW Buffer | 1.5 ml | 20 ml | 40 ml |\n| Wash Buffer (concentrate) | 1.5 ml | 15 ml | 30 ml |\n| RNase-free Water | 1 ml | 10 ml | 20 ml |\n| DNase I | 4 ul | 50 ul | 100 ul |\n| PR Column | 4 pcs | 50 pcs | 100 pcs |\n| Collection Tube | 8 pcs | 100 pcs | 200 pcs |\n| User Manual | 1 | 1 | 1 |",
    procedure: "1. Grind plant tissue (up to 100 mg) in liquid nitrogen.\n2. Add 450 ul PRK Buffer. Vortex vigorously.\n3. Incubate at room temperature for 5 minutes.\n4. Centrifuge at full speed for 5 minutes. Transfer supernatant.\n5. Add equal volume of ethanol (70%). Mix.\n6. Transfer to PR Column. Centrifuge.\n7. Add DNase I mixture. Incubate 15 minutes at room temperature.\n8. Wash with RW Buffer, then Wash Buffer.\n9. Dry column. Elute with RNase-free Water.",
    specifications: "Sample size: up to 100 mg plant tissue or 1 x 10^7 plant cells\nOptimized for plant tissue with high polysaccharide and polyphenol content\nIncludes on-column DNase I digestion\nHigh-quality total RNA suitable for RT-PCR, qPCR, RNA-seq, and Northern blotting\n\nImportant Notes:\n- Use RNase-free consumables and work in an RNase-free environment.\n- Add ethanol to Wash Buffer before first use.",
    troubleshooting: "Low RNA yield:\n- Ensure thorough tissue grinding in liquid nitrogen.\n- Verify sample does not exceed recommended amount.\n\nRNA degradation:\n- Work in RNase-free environment.\n- Use RNase Destroyer on all surfaces before starting.",
    image: "/images/products/invirogens-placeholder.svg",
    featured: false,
  },
  {
    name: "Blood/Cultured Cell Total RNA Mini Kit",
    slug: "blood-cultured-cell-rna-mini-kit",
    catalogNumber: "APBRK004/050/100",
    category: "RNA Extraction",
    shortDescription: "For isolation of RNA from whole blood, animal cells/tissues, bacteria, yeast, paraffin-fixed samples, fungi, and RNA clean-up.",
    description: "INVIROGENS \u03B1+ Solution\u2122 Blood/Cultured Cell Total RNA Mini Kit.\nAvailable in 4 preps (APBRK004), 50 preps (APBRK050), and 100 preps (APBRK100).\nSample size: 300 \u03BCl.",
    components: "| | APBRK 004 (4 preps) | APBRK 050 (50 preps) | APBRK 100 (100 preps) |\n|---|---|---|---|\n| BRK Buffer | 2 ml | 25 ml | 50 ml |\n| RW Buffer | 1.5 ml | 20 ml | 40 ml |\n| Wash Buffer (concentrate) | 1.5 ml | 15 ml | 30 ml |\n| RNase-free Water | 1 ml | 10 ml | 20 ml |\n| DNase I | 4 ul | 50 ul | 100 ul |\n| BR Column | 4 pcs | 50 pcs | 100 pcs |\n| Collection Tube | 8 pcs | 100 pcs | 200 pcs |\n| User Manual | 1 | 1 | 1 |",
    procedure: "1. Add 300 ul of blood sample to a 1.5 ml tube.\n2. Add 300 ul BRK Buffer. Vortex.\n3. Incubate at room temperature for 5 minutes.\n4. Add 300 ul ethanol (70%). Mix well.\n5. Transfer to BR Column. Centrifuge.\n6. Add DNase I. Incubate 15 minutes.\n7. Wash with RW Buffer, then Wash Buffer.\n8. Dry column. Elute with 30-50 ul RNase-free Water.",
    specifications: "Sample size: 300 ul blood or cultured cells\nSimple, rapid, and efficient isolation\nIncludes on-column DNase I digestion\nHigh-quality total RNA suitable for RT-PCR, qPCR, RNA-seq\n\nImportant Notes:\n- Work in RNase-free environment.\n- Add ethanol to Wash Buffer before first use.",
    troubleshooting: "Low RNA yield:\n- Use fresh blood sample. Older samples yield less RNA.\n- Ensure complete lysis.\n\nGenomic DNA contamination:\n- Ensure DNase I digestion step was performed.\n- Extend DNase I incubation time to 30 minutes if needed.",
    image: "/images/products/blood-cultured-cell-rna-mini-kit.jpg",
    featured: false,
  },
  {
    name: "Tissue Total RNA Mini Kit",
    slug: "tissue-total-rna-mini-kit",
    catalogNumber: "APTRK004/050/100",
    category: "RNA Extraction",
    shortDescription: "For isolation of RNA from animal cells/tissues, bacteria, yeast, paraffin-fixed samples, fungi, and RNA clean-up.",
    description: "INVIROGENS \u03B1+ Solution\u2122 Tissue Total RNA Mini Kit.\nAvailable in 4 preps (APTRK004), 50 preps (APTRK050), and 100 preps (APTRK100).",
    components: "| | APTRK 004 (4 preps) | APTRK 050 (50 preps) | APTRK 100 (100 preps) |\n|---|---|---|---|\n| TRK Buffer | 2 ml | 25 ml | 50 ml |\n| RW Buffer | 1.5 ml | 20 ml | 40 ml |\n| Wash Buffer (concentrate) | 1.5 ml | 15 ml | 30 ml |\n| RNase-free Water | 1 ml | 10 ml | 20 ml |\n| DNase I | 4 ul | 50 ul | 100 ul |\n| TR Column | 4 pcs | 50 pcs | 100 pcs |\n| Collection Tube | 8 pcs | 100 pcs | 200 pcs |\n| User Manual | 1 | 1 | 1 |",
    procedure: "1. Homogenize tissue sample in 450 ul TRK Buffer.\n2. Centrifuge at full speed for 5 minutes. Transfer supernatant.\n3. Add equal volume of ethanol (70%). Mix well.\n4. Transfer to TR Column. Centrifuge.\n5. Add DNase I. Incubate 15 minutes at room temperature.\n6. Wash with RW Buffer, then Wash Buffer.\n7. Dry column by centrifugation.\n8. Elute with 30-50 ul RNase-free Water.",
    specifications: "Optimized lysis and purification for various tissue types\nIncludes on-column DNase I digestion\nHigh-quality total RNA suitable for RT-PCR, qPCR, RNA-seq, and Northern blotting\n\nImportant Notes:\n- Thoroughly homogenize tissue for maximum RNA yield.\n- Work in RNase-free environment.",
    troubleshooting: "Low RNA yield:\n- Ensure complete tissue homogenization.\n- Use fresh tissue or properly stored (-80\u00B0C) tissue.\n\nRNA degradation:\n- Work in RNase-free environment.\n- Process tissue quickly after collection or store in RNA stabilization solution.",
    image: "/images/products/tissue-total-rna-mini-kit.jpg",
    featured: false,
  },
  {
    name: "RNA Stabilization Solution",
    slug: "rna-stabilization-solution",
    catalogNumber: "APRSS001",
    category: "RNA Extraction",
    shortDescription: "RNA Solution makes it possible for researchers to postpone RNA isolation for days, weeks, or even months after tissue collection without sacrificing RNA integrity",
    description: "INVIROGENS RNA Stabilization Solution.\nRNA Solution makes it possible for researchers to postpone RNA isolation for days, weeks, or even months after tissue collection without sacrificing RNA integrity.",
    components: "APRSS001 | RNA Stabilization Solution: 1 x 100 ml bottle",
    procedure: "1. Immediately after tissue collection, submerge specimens in RNA Stabilization Solution.\n2. Use approximately 10 volumes of solution per volume of tissue.\n3. Store at 4\u00B0C for short-term (up to 1 week) or -20\u00B0C for long-term storage.\n4. When ready for RNA isolation, remove tissue from solution and proceed with standard RNA extraction protocol.",
    specifications: "Makes it possible to postpone RNA isolation for days, weeks, or even months after tissue collection without sacrificing RNA integrity.\nCompatible with downstream RNA extraction kits and protocols.\nSimply submerge tissue specimens immediately after collection.",
    troubleshooting: "RNA degradation despite using stabilization solution:\n- Ensure tissue was submerged immediately after collection.\n- Use sufficient volume of solution (10x tissue volume).\n- Check storage temperature.",
    image: "/images/products/rna-stabilization-solution.jpg",
    featured: false,
  },
  {
    name: "Tri-RNA Reagent",
    slug: "tri-rna-reagent",
    catalogNumber: "APTRR001",
    category: "RNA Extraction",
    shortDescription: "Tri-RNA Reagent is a reagent from the improved phenol and guanidine isothiocyanate (GSN) method for the single-step RNA isolation",
    description: "INVIROGENS Tri-RNA Reagent.\nTri-RNA Reagent is a reagent from the improved phenol and guanidine isothiocyanate (GSN) method for the single-step RNA isolation.",
    components: "APTRR001 | Tri-RNA Reagent: 1 x 100 ml bottle",
    procedure: "1. Homogenize tissue or lyse cells in Tri-RNA Reagent (1 ml per 50-100 mg tissue).\n2. Incubate for 5 minutes at room temperature.\n3. Add 0.2 ml chloroform per 1 ml Tri-RNA Reagent. Shake vigorously for 15 seconds.\n4. Incubate at room temperature for 2-3 minutes.\n5. Centrifuge at 12,000 x g for 15 minutes at 4\u00B0C.\n6. Transfer upper aqueous phase to a new tube.\n7. Add 0.5 ml isopropanol per 1 ml Tri-RNA Reagent. Mix.\n8. Incubate for 10 minutes at room temperature.\n9. Centrifuge at 12,000 x g for 10 minutes at 4\u00B0C.\n10. Wash pellet with 75% ethanol. Air dry. Dissolve in RNase-free water.",
    specifications: "Improved phenol and guanidine isothiocyanate (GSN) method\nSingle-step RNA isolation\nSuitable for various biological sources\nHigh-quality RNA for RT-PCR, qPCR, and downstream applications\n\nImportant Notes:\n- Work in a fume hood when using this reagent.\n- Use RNase-free consumables.",
    troubleshooting: "Low RNA yield:\n- Ensure sufficient homogenization.\n- Use correct ratio of reagent to tissue.\n\nDNA contamination:\n- Avoid disturbing the interphase during aqueous phase transfer.\n- Treat with DNase I after isolation.",
    image: "/images/products/tri-rna-reagent.jpg",
    featured: false,
  },
  {
    name: "Straight PCR Lysis Reagent (Cell)",
    slug: "straight-pcr-lysis-reagent-cell",
    catalogNumber: "APDIC100",
    category: "Straight PCR",
    shortDescription: "Single-tube system for rapid preparation of DNA from mouse culture cells for direct PCR.",
    description: "INVIROGENS \u03B1+ Solution\u2122 Straight PCR Lysis Reagent (Cell).\nCatalog Number: APDIC100 (100 preps).\nStraight PCR DNA Extraction System is a single-tube system for rapid preparation of DNA from mouse culture cells.",
    components: "APDIC100 | Straight PCR Lysis Reagent (Cell): 100 preps\nIncludes: Lysis Buffer, Neutralization Buffer, tubes",
    procedure: "1. Collect cell sample (up to 10^6 cells).\n2. Add 50 ul of Lysis Buffer to the cell pellet. Mix by pipetting.\n3. Incubate at 95\u00B0C for 10 minutes.\n4. Add 50 ul of Neutralization Buffer. Mix.\n5. Centrifuge briefly.\n6. Use 1-5 ul of the lysate directly as template for PCR amplification.",
    specifications: "Single-tube system for rapid DNA preparation from cultured cells\nNo DNA extraction or purification required\nLysis reagent does not inhibit downstream PCR\nIdeal for high-throughput screening and genotyping\nResults in 30 minutes from sample to PCR-ready template",
    troubleshooting: "No PCR product:\n- Ensure correct incubation temperature (95\u00B0C).\n- Increase template volume (up to 5 ul).\n- Verify PCR conditions and primer design.\n\nWeak PCR bands:\n- Use more cells as starting material.\n- Optimize PCR cycling conditions.",
    image: "/images/products/straight-pcr-lysis-reagent-cell.jpg",
    featured: false,
  },
  {
    name: "Straight PCR Lysis Reagent (Ear)",
    slug: "straight-pcr-lysis-reagent-ear",
    catalogNumber: "APDIE100",
    category: "Straight PCR",
    shortDescription: "Single-tube system for rapid preparation of DNA from mouse ear pieces for direct PCR.",
    description: "INVIROGENS \u03B1+ Solution\u2122 Straight PCR Lysis Reagent (Ear).\nCatalog Number: APDIE100 (100 preps).\nStraight PCR DNA Extraction System is a single-tube system for rapid preparation of DNA from mouse ear pieces.",
    components: "APDIE100 | Straight PCR Lysis Reagent (Ear): 100 preps\nIncludes: Lysis Buffer, Neutralization Buffer, tubes",
    procedure: "1. Cut a small piece of mouse ear (1-2 mm punch).\n2. Add 50 ul of Lysis Buffer to the ear piece. Mix.\n3. Incubate at 95\u00B0C for 30 minutes.\n4. Add 50 ul of Neutralization Buffer. Mix.\n5. Centrifuge briefly.\n6. Use 1-5 ul of the lysate directly for PCR.",
    specifications: "Single-tube system for rapid DNA preparation from mouse ear pieces\nNo DNA extraction or purification required\nLysis reagent does not inhibit downstream PCR\nIdeal for mouse genotyping workflows",
    troubleshooting: "No PCR product:\n- Extend incubation time to 45 minutes for tough tissue.\n- Ensure tissue is fully submerged in Lysis Buffer.\n- Increase template volume.",
    image: "/images/products/straight-pcr-lysis-reagent-ear.jpg",
    featured: false,
  },
  {
    name: "Straight PCR Lysis Reagent (Mouse Tail)",
    slug: "straight-pcr-lysis-reagent-mouse-tail",
    catalogNumber: "APDIT100",
    category: "Straight PCR",
    shortDescription: "Single-tube system for rapid preparation of DNA from mouse tails for direct PCR.",
    description: "INVIROGENS \u03B1+ Solution\u2122 Straight PCR Lysis Reagent (Mouse Tail).\nCatalog Number: APDIT100 (100 preps).\nStraight PCR DNA Extraction System is a single-tube system for rapid preparation of DNA from mouse tails.",
    components: "APDIT100 | Straight PCR Lysis Reagent (Mouse Tail): 100 preps\nIncludes: Lysis Buffer, Neutralization Buffer, tubes",
    procedure: "1. Cut 0.5-1 cm of mouse tail tip.\n2. Add 100 ul of Lysis Buffer to the tail piece.\n3. Incubate at 95\u00B0C for 30 minutes. Vortex occasionally.\n4. Add 100 ul of Neutralization Buffer. Mix well.\n5. Centrifuge briefly to pellet debris.\n6. Use 1-5 ul of clear supernatant directly for PCR.",
    specifications: "Single-tube system for rapid DNA preparation from mouse tails\nNo DNA extraction or purification required\nLysis reagent does not inhibit downstream PCR\nIdeal for routine mouse genotyping\nFast turnaround from tail biopsy to PCR result",
    troubleshooting: "No PCR product:\n- Extend lysis time for older mice (thicker tails).\n- Increase Lysis Buffer volume for larger tail pieces.\n- Vortex more frequently during incubation.",
    image: "/images/products/straight-pcr-lysis-reagent-mouse-tail.jpg",
    featured: true,
  },
  {
    name: "Straight PCR Lysis Reagent (Yolk Sac)",
    slug: "straight-pcr-lysis-reagent-yolk-sac",
    catalogNumber: "APDIY100",
    category: "Straight PCR",
    shortDescription: "Single-tube system for rapid preparation of DNA from mouse yolk sac for direct PCR.",
    description: "INVIROGENS \u03B1+ Solution\u2122 Straight PCR Lysis Reagent (Yolk Sac).\nCatalog Number: APDIY100 (100 preps).\nStraight PCR DNA Extraction System is a single-tube system for rapid preparation of DNA from mouse yolk sac.",
    components: "APDIY100 | Straight PCR Lysis Reagent (Yolk Sac): 100 preps\nIncludes: Lysis Buffer, Neutralization Buffer, tubes",
    procedure: "1. Collect yolk sac tissue.\n2. Add 50 ul of Lysis Buffer. Mix by pipetting.\n3. Incubate at 95\u00B0C for 20 minutes.\n4. Add 50 ul of Neutralization Buffer. Mix.\n5. Centrifuge briefly.\n6. Use 1-5 ul directly for PCR.",
    specifications: "Single-tube system for rapid DNA preparation from mouse yolk sac\nNo DNA extraction or purification required\nLysis reagent does not inhibit downstream PCR\nIdeal for embryonic genotyping applications",
    troubleshooting: "No PCR product:\n- Ensure complete tissue lysis.\n- Increase template volume.\n- Optimize PCR conditions.",
    image: "/images/products/straight-pcr-lysis-reagent-yolk-sac.jpg",
    featured: false,
  },
  {
    name: "Viral Nucleic Acid Extraction Kit",
    slug: "viral-nucleic-acid-extraction-kit",
    catalogNumber: "APVNK004/050/100",
    category: "Viral Nucleic Acid",
    shortDescription: "carrier RNA provided, for low viral load specimen",
    description: "INVIROGENS \u03B1+ Solution\u2122 Viral Nucleic Acid Extraction Kit.\nAvailable in 4 preps (APVNK004), 50 preps (APVNK050), and 100 preps (APVNK100).\nCarrier RNA provided, for low viral load specimen.\nSample size: up to 150 \u03BCl of serum or cell-free supernatant of cell culture.",
    components: "| | APVNK 004 (4 preps) | APVNK 050 (50 preps) | APVNK 100 (100 preps) |\n|---|---|---|---|\n| VN Buffer | 2 ml | 25 ml | 50 ml |\n| VW Buffer | 1.5 ml | 20 ml | 40 ml |\n| Wash Buffer (concentrate) | 1.5 ml | 15 ml | 30 ml |\n| RNase-free Water | 1 ml | 10 ml | 20 ml |\n| Carrier RNA | 50 ul | 300 ul | 600 ul |\n| VN Column | 4 pcs | 50 pcs | 100 pcs |\n| Collection Tube | 8 pcs | 100 pcs | 200 pcs |\n| User Manual | 1 | 1 | 1 |",
    procedure: "1. Add 25 ul Carrier RNA to 150 ul sample (serum or cell-free supernatant).\n2. Add 400 ul VN Buffer. Vortex for 15 seconds.\n3. Incubate at room temperature for 10 minutes.\n4. Add 400 ul ethanol (96-100%). Mix well.\n5. Transfer to VN Column. Centrifuge.\n6. Wash with VW Buffer, then Wash Buffer.\n7. Dry column by centrifugation.\n8. Elute with 30-60 ul preheated (70\u00B0C) RNase-free Water.",
    specifications: "Carrier RNA provided for low viral load specimens\nSample size: up to 150 ul of serum or cell-free supernatant\nSimultaneous extraction of viral DNA and RNA\nOptimized for serum, plasma, nasopharyngeal swabs, and body fluids\nHigh sensitivity detection with low elution volumes\nCompatible with RT-PCR, qPCR, and next-generation sequencing\n\nImportant Notes:\n- Add ethanol to Wash Buffer before first use.\n- Work in RNase-free environment.",
    troubleshooting: "Low viral nucleic acid yield:\n- Use Carrier RNA for low viral load specimens.\n- Ensure fresh sample or properly stored sample.\n- Pre-heat elution buffer to 70\u00B0C.\n\nPCR inhibition:\n- Ensure complete washing steps.\n- Dry column thoroughly before elution.",
    image: "/images/products/viral-nucleic-acid-extraction-kit.jpg",
    featured: true,
  },
  {
    name: "CD63 Exosome ELISA Kit, Human",
    slug: "cd63-exosome-elisa-kit",
    catalogNumber: "APCD63",
    category: "Exosome ELISA Kit",
    shortDescription: "CD63 exosome quantification kit with indirect ELASA workflow and 96-well plate format.",
    description: "INVIROGENS CD63 Exosome ELISA Kit, Human.\nStorage temperature: 4 C.\nSufficient to create 3 standard curves with n = 2.\nExosome Protein Standard period after opening: 3 months.\nIf the 96-well plate is not used completely in one experiment, remove unused strips and store in the aluminum foil bag.\nStore reagents immediately after use.",
    components: "| Component | Quantity |\n|---|---|\n| Exosome Protein Standard (Blue cap) | 30 uL |\n| Coating Buffer | 20 mL |\n| Blocking Buffer | 40 mL |\n| CD63 Probe (Green cap) | 10 uL |\n| HRP-conjugated Secondary Probe (Red cap) | 10 uL |\n| Probe Dilution Buffer | 40 mL |\n| Wash Buffer (10X) | 50 mL |\n| Substrate Buffer | 12 mL |\n| Stop Buffer | 12 mL |\n| 96 Well Plate | 1 plate (16-well x 6 strips) |\n\nMaterials Not Included in the Kit:\n- Microtiter plate sealing film/cover\n- Micropipettes (10 to 1000 uL)\n- Multichannel micropipette (recommended)\n- Multichannel micropipette reservoir\n- Microtiter plate shaker\n- Microplate reader (capable of measuring at 450 nm)\n- Plate washer",
    procedure: "Before starting:\n1. Fresh dilute CD63 Probe (2500X) to 2500-fold in Probe Dilution Buffer before step 6 (example: for 1 plate, add 4 uL CD63 Probe into 10 mL assay buffer).\n2. Fresh dilute HRP-conjugated Secondary Probe (2500X) to 2500-fold in Probe Dilution Buffer before step 8 (example: for 1 plate, add 4 uL probe into 10 mL assay buffer).\n\nELASA assay:\n1. Add 100 uL freshly prepared standard dilutions and exosome samples to the 96-well plate.\n2. Seal plate and incubate at 4 C overnight.\n3. Discard solution and wash each well with 350 uL 1X wash buffer; repeat 3x. Tap dry on lint-free paper towel.\n4. Add 300 uL blocking buffer to each well. Incubate 1 hour at room temperature on shaker (100 rpm).\n5. Wash each well 3x with 350 uL 1X wash buffer.\n6. Add 100 uL dilute CD63 Probe (1X) to each well. Incubate 1 hour at room temperature on shaker (100 rpm).\n7. Wash each well 3x with 350 uL 1X wash buffer.\n8. Add 100 uL dilute HRP-conjugated Secondary Probe (1X). Incubate 1 hour at room temperature on shaker (100 rpm).\n9. Warm substrate buffer to room temperature.\n10. Wash each well 3x with 350 uL 1X wash buffer.\n11. Add 100 uL substrate buffer to each well, incubate in dark for 15 minutes, then add 100 uL stop buffer and read immediately.\n12. Measure absorbance at 450 nm.\n13. Plot standard curve as mean OD450 and calculate sample concentration.",
    specifications: "Indirect ELASA assay format for exosome quantification.\nCaptured exosomes bind CD63 probe, followed by HRP-conjugated secondary probe and substrate-based color development.\nColorimetric signal is measured by microplate reader at 450 nm.\nNote: Do not aspirate directly from the bottom of wells during wash steps.",
    troubleshooting: "| Problem | Possible Cause | Solution |\n|---|---|---|\n| Weak or no signal | Protein amount in well is insufficient | Ensure extracts contain enough protein |\n| Weak or no signal | Incubation time/temperature is incorrect | Follow protocol incubation conditions exactly |\n| Weak or no signal | Inadequate reagent volumes or improper dilution | Check pipettes and prepare reagents correctly |\n| High background | Contaminated wash buffer | Prepare fresh wash buffer |\n| High background | Insufficient washing | Follow full wash cycles as specified |\n| Anomalous signal | Reagents not fresh or wrong pH | Use freshly prepared reagents |\n| Anomalous signal | Reagent order/preparation incorrect | Review protocol and confirm concentrations |\n| Anomalous signal | Bubbles in wells | Remove air bubbles before reading |\n| Anomalous signal | Uneven local temperature | Avoid variable environmental conditions |\n| Anomalous signal | Contamination on plate bottom | Keep plate bottom clean, remove fingerprints/residual liquid |\n| Low OD values | Incorrect microplate reader settings | Check wavelength/filter settings and preheat reader |\n| Low sensitivity | Improper storage of kit | Store reagents as instructed |\n| Low sensitivity | Stop solution not added before reading | Add stop solution before OD reading |",
    image: "/images/products/invirogens-placeholder.svg",
    featured: false,
  },
  {
    name: "CD9 Exosome ELISA Kit, Human",
    slug: "cd9-exosome-elisa-kit",
    catalogNumber: "APCD9",
    category: "Exosome ELISA Kit",
    shortDescription: "CD9 exosome quantification kit with indirect ELASA workflow and 96-well plate format.",
    description: "INVIROGENS CD9 Exosome ELISA Kit, Human.\nStorage temperature: 4 C.\nSufficient to create 3 standard curves with n = 2.\nExosome Protein Standard period after opening: 3 months.\nIf the 96-well plate is not used completely in one experiment, remove unused strips and store in the aluminum foil bag.\nStore reagents immediately after use.",
    components: "| Component | Quantity |\n|---|---|\n| Exosome Protein Standard (Blue cap) | 30 uL |\n| Coating Buffer | 20 mL |\n| Blocking Buffer | 40 mL |\n| CD9 Probe (Green cap) | 10 uL |\n| HRP-conjugated Secondary Probe (Red cap) | 10 uL |\n| Probe Dilution Buffer | 40 mL |\n| Wash Buffer (10X) | 50 mL |\n| Substrate Buffer | 12 mL |\n| Stop Buffer | 12 mL |\n| 96 Well Plate | 1 plate (16-well x 6 strips) |\n\nMaterials Not Included in the Kit:\n- Microtiter plate sealing film/cover\n- Micropipettes (10 to 1000 uL)\n- Multichannel micropipette (recommended)\n- Multichannel micropipette reservoir\n- Microtiter plate shaker\n- Microplate reader (capable of measuring at 450 nm)\n- Plate washer",
    procedure: "Before starting:\n1. Fresh dilute CD9 Probe (2500X) to 2500-fold in Probe Dilution Buffer before step 6 (example: for 1 plate, add 4 uL CD9 Probe into 10 mL assay buffer).\n2. Fresh dilute HRP-conjugated Secondary Probe (2500X) to 2500-fold in Probe Dilution Buffer before step 8 (example: for 1 plate, add 4 uL probe into 10 mL assay buffer).\n\nELASA assay:\n1. Add 100 uL freshly prepared standard dilutions and exosome samples to the 96-well plate.\n2. Seal plate and incubate at 4 C overnight.\n3. Discard solution and wash each well with 350 uL 1X wash buffer; repeat 3x. Tap dry on lint-free paper towel.\n4. Add 300 uL blocking buffer to each well. Incubate 1 hour at room temperature on shaker (100 rpm).\n5. Wash each well 3x with 350 uL 1X wash buffer.\n6. Add 100 uL dilute CD9 Probe (1X) to each well. Incubate 1 hour at room temperature on shaker (100 rpm).\n7. Wash each well 3x with 350 uL 1X wash buffer.\n8. Add 100 uL dilute HRP-conjugated Secondary Probe (1X). Incubate 1 hour at room temperature on shaker (100 rpm).\n9. Warm substrate buffer to room temperature.\n10. Wash each well 3x with 350 uL 1X wash buffer.\n11. Add 100 uL substrate buffer to each well, incubate in dark for 15 minutes, then add 100 uL stop buffer and read immediately.\n12. Measure absorbance at 450 nm.\n13. Plot standard curve as mean OD450 and calculate sample concentration.",
    specifications: "Indirect ELASA assay format for exosome quantification.\nCaptured exosomes bind CD9 probe, followed by HRP-conjugated secondary probe and substrate-based color development.\nColorimetric signal is measured by microplate reader at 450 nm.\nNote: Do not aspirate directly from the bottom of wells during wash steps.",
    troubleshooting: "| Problem | Possible Cause | Solution |\n|---|---|---|\n| Weak or no signal | Protein amount in well is insufficient | Ensure extracts contain enough protein |\n| Weak or no signal | Incubation time/temperature is incorrect | Follow protocol incubation conditions exactly |\n| Weak or no signal | Inadequate reagent volumes or improper dilution | Check pipettes and prepare reagents correctly |\n| High background | Contaminated wash buffer | Prepare fresh wash buffer |\n| High background | Insufficient washing | Follow full wash cycles as specified |\n| Anomalous signal | Reagents not fresh or wrong pH | Use freshly prepared reagents |\n| Anomalous signal | Reagent order/preparation incorrect | Review protocol and confirm concentrations |\n| Anomalous signal | Bubbles in wells | Remove air bubbles before reading |\n| Anomalous signal | Uneven local temperature | Avoid variable environmental conditions |\n| Anomalous signal | Contamination on plate bottom | Keep plate bottom clean, remove fingerprints/residual liquid |\n| Low OD values | Incorrect microplate reader settings | Check wavelength/filter settings and preheat reader |\n| Low sensitivity | Improper storage of kit | Store reagents as instructed |\n| Low sensitivity | Stop solution not added before reading | Add stop solution before OD reading |",
    image: "/images/products/invirogens-placeholder.svg",
    featured: false,
  },
];

export const seedNews = [
  {
    title: "Wide Mouth Bottle PP",
    slug: "wide-mouth-bottle-pp",
    excerpt: "Autoclavable wide mouth polypropylene bottles are rigid, translucent and have excellent contact clarity. Available in multiple sizes.",
    content: "INVIROGENS is pleased to introduce our new line of Wide Mouth Polypropylene Laboratory Bottles, designed to meet the demanding requirements of modern research and clinical laboratories.\nAutoclavable wide mouth polypropylene bottles are rigid, translucent and have excellent contact clarity. Polypropylene caps include a built-in sealing ring for leak-proof performance.\nThe wide mouth design facilitates easy filling, pouring, and cleaning. All bottles are fully autoclavable at 121 degrees Celsius for 20 minutes.\nAvailable in 125 mL, 250 mL, 500 mL, and 1000 mL sizes. Graduated markings provide convenient volume measurement during use.\nIdeal for media preparation, chemical storage, buffer solutions, and general laboratory use.",
    image: "/images/category-dna.jpg",
    publishedAt: new Date("2022-04-11"),
  },
  {
    title: "15 ml Centrifuge Tubes with Snap Cap",
    slug: "centrifuge-tubes-snap-cap",
    excerpt: "The tubes handle small amounts of liquid and are designed for storage, spinning down, as reaction vessels, or for separating samples.",
    content: "INVIROGENS 15 ml Centrifuge Tubes with Snap Cap are designed for your laboratory needs.\nThe tubes handle small amounts of liquid and are designed for storage, spinning down, as reaction vessels, or for separating samples.\nThe innovative snap cap design allows secure one-handed closure and opening, reducing the risk of cross-contamination when processing multiple samples.\nManufactured from high-clarity polypropylene with excellent chemical resistance, withstanding centrifugation forces up to 6000 x g.\nClear graduation marks are printed with solvent-resistant ink. Certified DNase-free, RNase-free, and pyrogen-free for sensitive molecular biology applications.\nAvailable in bulk packs of 500 units and individually wrapped sterile packs of 50 units.",
    image: "/images/category-dna.jpg",
    publishedAt: new Date("2022-04-08"),
  },
  {
    title: "INVIROGENS EtBr Destroyer - Degrades EtBr, SYBR Green, SYBR Gold, SYBR Orange",
    slug: "etbr-destroyer-degrades-multiple",
    excerpt: "INVIROGENS EtBr Destroyer is a laboratory reagent intended for the removal and destruction of Ethidium Bromide contamination. It can also degrade SYBR Green, SYBR Gold, and SYBR Orange.",
    content: "INVIROGENS EtBr Destroyer is a laboratory reagent intended for the removal and destruction of Ethidium Bromide contamination.\nIt can also effectively degrade SYBR Green I, SYBR Gold, and SYPRO Orange stains used in nucleic acid detection.\nThe EtBr Destroyer is available in two formats: the Destroyer Bag for liquid contaminant treatment, and the Destroyer Sprayer for solid waste and surface decontamination.\nThe effect can be monitored and confirmed by UV light exposure whereby once the EtBr has been destroyed the fluorescence will disappear.\nSafe: Demonstrated by Ames test to safely and effectively destroy EtBr without any mutagenic effect. The AMES test result data supports that the genotoxicity was reduced significantly.\nThis product provides an effective, economical, and environmentally responsible solution for managing hazardous nucleic acid stain waste in the laboratory.",
    image: "/images/category-etbr.jpg",
    publishedAt: new Date("2020-06-26"),
  },
  {
    title: "INVIROGENS EtBr Destroyer - You Can Even Re-Use Your Buffer After Treatment",
    slug: "etbr-destroyer-reuse-buffer",
    excerpt: "INVIROGENS EtBr Destroyer is a specifically designed reagent to effectively degrade and destroy Ethidium Bromide, resulting in non-mutagenic and non-hazardous byproducts.",
    content: "INVIROGENS EtBr Destroyer is a specifically designed reagent to effectively degrade and destroy Ethidium Bromide and result in both non-mutagenic and non-hazardous waste.\nOne of the big economical benefits of using this product is that after using the INVIROGENS EtBr Destroyer, the once-contaminated buffer can be filtrated and used again without worry.\nEconomical: INVIROGENS EtBr Destroyer Sprayer bottles can be refilled after use and the bags are available in both a 10 and 20 pack. In comparison to the costs associated with properly disposing of hazardous materials, the EtBr Destroyer products save your money in the long run.\nSafe: INVIROGENS EtBr Destroyer has been demonstrated by Ames test to safely and effectively destroy EtBr without any mutagenic effect.\nThe AMES test result data supports that the genotoxicity of EtBr contaminated solution, treated by both the INVIROGENS EtBr Destroyer Bag and Sprayer was reduced significantly and a negative result was determined.",
    image: "/images/category-etbr.jpg",
    publishedAt: new Date("2020-06-26"),
  },
];

export async function seedDatabase() {
  console.log(`In-memory seed ready: ${seedProducts.length} products, ${seedNews.length} news items.`);
}
